name: Generate CML Report

on: [push]

jobs:
  generate_cml_report:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: 
      image: ghcr.io/moja-global/rest_api_gcbm:master
      ports:
        - "8080:8080"
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: test-cml
          
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Run Moja CLI
        id: run_moja_cli
        run: |
          apt-get update && apt-get install unzip tree
          pushd local/rest_api_gcbm/tests/
          unzip linux-demo.zip
          cd config/
          tree
          /opt/gcbm/moja.cli --config_file gcbm_config.cfg --config_provider provider_config.json
          popd
          cd local/rest_api_gcbm
          mkdir GCBM.CompileResults
          
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: moja-global/GCBM.CompileResults
          path: local/rest_api_gcbm/GCBM.CompileResults
          
      - name: Compile results
        run: |
          cd local/rest_api_gcbm
          tree
          python3 GCBM.CompileResults/compileresults.py sqlite:///tests/output/gcbm_output.db --output_db sqlite:///tests/output/compiled_simulation_output.db
          
      - name: Yo
        run: pip3 install pandas matplotlib
        
      - name: Setup CML
        uses: iterative/setup-cml@v1
        
      - name: Send the report
        env:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
         cd local/rest_api_gcbm
         tree
         python3 annual_summaries.py
         echo "# GCBM Model" > report.md
         echo "## Total Biomass Curve" >> report.md
         cml-publish output/total_biomass_mt.png --md >> report.md
         cml-send-comment report.md 
